INFO:waitress:Serving on http://0.0.0.0:8080
INFO:waitress:Serving on http://0.0.0.0:8080
INFO:waitress:Serving on http://0.0.0.0:8080
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
INFO:waitress:Serving on http://0.0.0.0:8080
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html')
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
ERROR:flaskr:Exception on /view/rwc [GET]
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rwc/Documents/SynCreator/flaskr/scc.py", line 140, in view
    resp = render_template('scc/' + settings[0] + '.html', settings = settings)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/rwc/Documents/SynCreator/flaskr/templates/scc/500.html", line 11, in top-level template code
    {% if settings[1] %}
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'settings' is undefined
Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/waitress/server.py", line 322, in run
    self.asyncore.loop(
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/waitress/wasyncore.py", line 245, in loop
    poll_fun(timeout, map)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/waitress/wasyncore.py", line 172, in poll
    r, w, e = select.select(r, w, e, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rwc/Documents/SynCreator/venv/bin/waitress-serve", line 8, in <module>
    sys.exit(run())
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/waitress/runner.py", line 298, in run
    _serve(app, **kw)
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/waitress/__init__.py", line 19, in serve
    server.run()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/waitress/server.py", line 328, in run
    self.task_dispatcher.shutdown()
  File "/Users/rwc/Documents/SynCreator/venv/lib/python3.9/site-packages/waitress/task.py", line 128, in shutdown
    self.thread_exit_cv.wait(0.1)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
